### ISSUE TITLE
Android13, Island-dev(after v6.1.2), getApplicationInfo not implemented in subclass

### ISSUE THREAD

**Issue by andy-math** [oasisfeng/condom#34]
```
Caused by: java.lang.UnsupportedOperationException: getApplicationInfo not implemented in subclass
at android.content.pm.PackageManager.getApplicationInfo(PackageManager.java:5441)
at com.google.firebase.sessions.settings.LocalOverrideSettings.<init>(LocalOverrideSettings.kt:31)
at com.google.firebase.sessions.settings.SessionsSettings.<init>(SessionsSettings.kt:41)
at com.google.firebase.sessions.FirebaseSessions.<init>(FirebaseSessions.kt:43)
at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-0(FirebaseSessionsRegistrar.kt:48)
at com.google.firebase.sessions.FirebaseSessionsRegistrar.$r8$lambda$JITndpZCWeA0w9BDlkcI3l22oGY(Unknown Source:0)
```

```
com.oasisfeng.island                 E  	at com.google.firebase.sessions.FirebaseSessionsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:0)
at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
at com.google.firebase.components.Lazy.get(Lazy.java:53)
at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:48)
at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:24)
at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:69)
at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
at com.google.firebase.components.Lazy.get(Lazy.java:53)
at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
at com.oasisfeng.island.firebase.FirebaseWrapper.<clinit>(FirebaseWrapper.java:45)
```
see https://github.com/oasisfeng/island/issues/446
missing override method com.oasisfeng.condom.PackageManagerWrapper#getApplicationInfo(String,ApplicationInfoFlags)
Island version: commit 2aab8f9d6e7ada845ecaa5fa8340180423949c30
Condom version: implementation 'com.oasisfeng.condom:library:2.5.0' in island:shared

**Comment by oasisfeng** [comment]
Fixed in b46858f1c38d4d2a5beceed52c52f08a670d8ab6

**Comment by oasisfeng** [comment]
Island will be upgraded to use version 3.0.0 soon.

**Comment by andy-math** [comment]
Thanks for your work. 😄
