### ISSUE TITLE
debug模式下友盟推送初始化闪退

### ISSUE THREAD

**Issue by zzwwws** [oasisfeng/condom#8]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference 
			at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1405)
			at android.provider.Settings$Secure.getStringForUser(Settings.java:4021)
			at android.provider.Settings$System.getStringForUser(Settings.java:1674)
			at android.provider.Settings$System.getString(Settings.java:1664)
			at com.umeng.message.common.UmengMessageDeviceConfig.getAndroidId(UmengMessageDeviceConfig.java:276)
			at com.umeng.message.common.b.a(Header.java:352)
			at com.umeng.message.common.b.b(Header.java:388)
			at com.umeng.message.UTrack.d(UTrack.java:615)
			at com.umeng.message.UTrack.<init>(UTrack.java:87)
			at com.umeng.message.UTrack.getInstance(UTrack.java:94)
			at com.umeng.message.PushAgent.setAppkeyAndSecret(PushAgent.java:544)

初始化代码如下：
```
        mPushAgent = PushAgent.getInstance(CondomContext.wrap(context, null));
        mPushAgent.setAppkeyAndSecret(umeng_key, umeng_secret);
```
看报错堆栈，Settings.java有这么一段：
```
        private IContentProvider lazyGetProvider(ContentResolver cr) {
            IContentProvider cp = null;
            synchronized (NameValueCache.this) {
                cp = mContentProvider;
                if (cp == null) {
                    cp = mContentProvider = cr.acquireProvider(mUri.getAuthority());
                }
            }
            return cp;
        }
```
可能是有多线程同时访问，导致cp可能返回null。但是release版本没问题，奇怪了。把初始化代码改成：
```
        mPushAgent = PushAgent.getInstance(context);
        mPushAgent.setAppkeyAndSecret(umeng_key, umeng_secret);
```
也没问题。

//update :
```
	boolean shouldAllowProvider(final @Nullable ProviderInfo provider) {
		if (provider == null) return false;
		if (mBase.getPackageName().equals(provider.packageName)) return true;
		if (shouldBlockRequestTarget(OutboundType.CONTENT, null, provider.packageName)) return mDryRun;
		if (SDK_INT >= HONEYCOMB_MR1 && mExcludeStoppedPackages && (provider.applicationInfo.flags & FLAG_STOPPED) != 0) return mDryRun;
		return true;
	}
```
从上面代码看，condom可能有误杀系统provider的可能。在vivo机型上，com.android.providers.settings这个applicationinfo满足 (provider.applicationInfo.flags & FLAG_STOPPED) != 0这个条件，所以在acquireProvider时，返回null。
ps：之所以和release，debug版本有关，是因为友盟有一个设置            mPushAgent.setDebugMode(AppConfig.debuggable());release版本可能绕过了acquireProvider这个地方。

**Comment by oasisfeng** [comment]
按理说，FLAG_STOPPED 在正常的手机上是不可能出现于com.android.providers.settings这个package，除非用户主动停止了这个package。因为任何package中的provider一旦被调用，FLAG_STOPPED状态就被清除了。

你的测试环境中是否有其它可能导致com.android.providers.settings被force stop的因素？

**Comment by oasisfeng** [comment]
鉴于这个情况不能排除客观上存在的可能性，我在考虑参考AOSP对于broadcast的处理方式，对privileged package中的content provider不再检查FLAG_STOPPED状态。

**Comment by zzwwws** [comment]
测试了vivo x9和vivo y66，都闪退，其他机型暂时没发现。怀疑是特定rom有这个现象

**Comment by zzwwws** [comment]
而且，vivo在测试环境下，com.android.providers.settings这个package也满足 (provider.applicationInfo.flags & FLAG_STOPPED) != 0这个条件

**Comment by oasisfeng** [comment]
谢谢反馈！我周末把上面提到的这个workaround加上。

**Comment by oasisfeng** [comment]
Fixed in commit 700647a9375c2690610b46e43700505061c9d69b

**Comment by zzwwws** [comment]
感谢~大概什么时候会发个release版本

**Comment by oasisfeng** [comment]
@zzwwws 上周已经 release 1.2.0 了，请验证。

**Comment by zzwwws** [comment]
已验证
